prepare_data.py:
  srs: "EPSG:2056"
  tiling:
    shapefile: ../input/input-test/[AOI_Shapefile]
  label:
    shapefile: ../input/input-test/tlm-hr-trn-topo.shp
  output_folder: ../output/output-trne

generate_tilesets.py:
  debug_mode: False
  datasets:
    aoi_tiles_geojson: ../output/output-trne/tiles.geojson
    ground_truth_labels_geojson: ../output/output-trne/labels.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://wms.geo.admin.ch/service
      layers: ch.swisstopo.swissimage
      srs: "EPSG:2056"
  output_folder: ../output/output-trne
  tile_size: 512 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Quarry and exploitation site detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:
    category:
        name: "Quarry"
        supercategory: "Land usage"

train_model.py:
    working_folder: ../output/output-trne
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: '../../config/detectron2_config_dqry.yaml' # path relative to the working_folder
    model_weights:
        model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"

make_detections.py:
  working_folder: ../output/output-trne
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files: # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: '../../config/detectron2_config_dqry.yaml' # path relative to the working_folder
  model_weights:
    pth_file: './logs/model_0002999.pth'
  image_metadata_json: '../output/output-trne/img_metadata.json'
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 2.0 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05

assess_detections.py:
  datasets:
    ground_truth_labels_geojson: ../output/output-trne/labels.geojson
    image_metadata_json: ../output/output-trne/img_metadata.json
    split_aoi_tiles_geojson: ../output/output-trne/split_aoi_tiles.geojson # aoi = Area of Interest
    detections:
      trn: ../output/output-trne/trn_detections_at_0dot05_threshold.gpkg
      val: ../output/output-trne/val_detections_at_0dot05_threshold.gpkg
      tst: ../output/output-trne/tst_detections_at_0dot05_threshold.gpkg
  output_folder: ../output/output-trne