prepare_data.py:
  srs: "EPSG:2056"
  tiling:
    shapefile: ../input/input-prd/[AoI_Shapefile]
  label:
    shapefile: ../input/input-prd/[AoI_Shapefile]
  output_folder: ../output/output-prd

generate_tilesets.py:
  debug_mode: True
  datasets:
    aoi_tiles_geojson: ../output/output-prd/tiles.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://wms.geo.admin.ch/service
      layers: ch.swisstopo.swissimage
      srs: "EPSG:2056"
  output_folder: ../output/output-prd
  tile_size: 512 # per side, in pixels
  overwrite: True
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Quarry and exploitation site detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:
    category:
        name: "Quarry"
        supercategory: "Land usage"

make_detections.py:
  working_folder: ../output/output-prd
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files: # relative paths, w/ respect to the working_folder
    oth: COCO_oth.json
  detectron2_config_file: '../../config/detectron2_config_dqry.yaml' # path relative to the working_folder
  model_weights:
    pth_file:  '../../input/input-prd/logs/model_0002999.pth'
  image_metadata_json: '../output/output-prd/img_metadata.json'
  rdp_simplification: # rdp = Ramer-Douglas-Peucker
    enabled: False
    epsilon: 2.0 # cf. https://rdp.readthedocs.io/en/latest/
  score_lower_threshold: 0.05