###  Identifying and tracking MES over time  ### 

# Track object in different datasets over years
track_detections.py:  
  years: [YEAR1, YEAR2, YEAR3,...]                         # Provide a list of years used for detection
  datasets:
    detection: ./output/det/detections_MES.gpkg  # Final detection file, produced by filter_detections.py
  output_folder: ./output/track/

# Plots
plots.py:  
  object_id: [ID_OBJECT1, ID_OBJECT2, ID_OBJECT3,...]       # Provide a list of id_object defined by track_detections.py
  plots: ['area-year'] 
  datasets:
    detection: ./output/track/detections_years.gpkg  # Object tracking file, produced by track_detections.py
  output_folder: ./output/track/plots